import { randomUUID } from 'node:crypto';
import type { Readable } from 'node:stream';

/**
 * Storage for large medical files (DICOM, whole-slide images, Grad-CAM images).
 * The relational database only keeps the key and metadata (proposal §3.3, L5).
 * Keys are always generated by the server; user-supplied filenames never become paths.
 */
export interface ObjectMetadata {
  contentType?: string;
  sha256?: string;
}

export interface ObjectStat {
  sizeBytes: number;
  contentType?: string;
}

export interface ObjectStorage {
  put(key: string, body: Readable, metadata: ObjectMetadata): Promise<void>;
  get(key: string): Promise<Readable>;
  stat(key: string): Promise<ObjectStat>;
  exists(key: string): Promise<boolean>;
  delete(key: string): Promise<void>;
}

export class ObjectNotFoundError extends Error {
  constructor(key: string) {
    super(`Object not found: ${key}`);
  }
}

// Lower-case segments of [a-z0-9_-], separated by single slashes, optional extension.
const KEY_PATTERN =
  /^[a-z0-9][a-z0-9_-]*(\/[a-z0-9][a-z0-9_-]*)*(\.[a-z0-9]{1,10})?$/;
const SEGMENT_PATTERN = /^[a-z0-9][a-z0-9_-]*$/;
const EXTENSION_PATTERN = /^\.[a-z0-9]{1,10}$/;

export function assertValidKey(key: string): void {
  if (key.length === 0 || key.length > 512 || !KEY_PATTERN.test(key)) {
    throw new Error(`Invalid object key: ${JSON.stringify(key)}`);
  }
}

/** e.g. `imaging/2026/09/<uuid>.dcm` */
export function generateObjectKey(
  prefix: string,
  extension = '',
  now = new Date(),
): string {
  if (!SEGMENT_PATTERN.test(prefix))
    throw new Error(`Invalid object key prefix: ${prefix}`);
  if (extension !== '' && !EXTENSION_PATTERN.test(extension)) {
    throw new Error(`Invalid object key extension: ${extension}`);
  }
  const yyyy = String(now.getUTCFullYear());
  const mm = String(now.getUTCMonth() + 1).padStart(2, '0');
  const key = `${prefix}/${yyyy}/${mm}/${randomUUID()}${extension}`;
  assertValidKey(key);
  return key;
}
