"""Writes the diagrams that are generated from the project itself, so they
always match it: the PostgreSQL entity-relationship diagrams (from
schema.prisma), the API map (from docs/access-matrix.md and the AI contract)
and the actual timeline (from the Git history). Standard library only.
"""

import re
import subprocess
from pathlib import Path

import contents as C

SCHEMA = "3-application-logic/backend/prisma/schema.prisma"
ACCESS_MATRIX = "docs/access-matrix.md"
AI_CONTRACT = "2-api-gateway/openapi/ai-contract.yaml"

#: The inputs whose changes make the generated diagrams out of date.
INPUTS = [SCHEMA, ACCESS_MATRIX, AI_CONTRACT]

HEADER = "' Generated by docs/report/tools/report.py (step diagrams) from {source}. Do not edit.\n"

SECTION_COLOURS = ["#eff6ff", "#ecfdf5", "#fef9c3", "#fdf2f8", "#f5f3ff", "#fff7ed"]


# --- PostgreSQL (Prisma schema) ---------------------------------------------


def _sql_type(prisma_type: str, attrs: str, enums: set[str]) -> str:
    if prisma_type in enums:
        return prisma_type
    if "@db.Uuid" in attrs:
        return "uuid"
    if "@db.Timestamptz" in attrs:
        return "timestamptz"
    if "@db.Date" in attrs:
        return "date"
    m = re.search(r"@db\.Decimal\((\d+),\s*(\d+)\)", attrs)
    if m:
        return f"numeric({m.group(1)},{m.group(2)})"
    return {
        "String": "text", "Int": "integer", "BigInt": "bigint", "Boolean": "boolean",
        "DateTime": "timestamp", "Decimal": "numeric", "Json": "jsonb", "Bytes": "bytea",
    }.get(prisma_type, prisma_type)


def parse_schema(text: str) -> tuple[list[dict], dict[str, list[str]]]:
    """Tables (in file order) and enums from a Prisma schema."""
    lines = text.splitlines()
    names = {m.group(2): m.group(1) for m in re.finditer(r"^(model|enum) (\w+) \{", text, re.M)}
    models = {n for n, kind in names.items() if kind == "model"}
    enum_names = {n for n, kind in names.items() if kind == "enum"}
    tables: list[dict] = []
    enums: dict[str, list[str]] = {}
    section = ""
    doc: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if re.match(r"^// -{10,}", line) and i + 2 < len(lines) and re.match(r"^// -{10,}", lines[i + 2].strip()):
            # "AI (registry, jobs, explainability). Full reports live..." → "AI (registry, jobs, explainability)"
            section = re.split(r"\.\s", lines[i + 1].strip().lstrip("/").strip())[0]
            i += 3
            continue
        if line.startswith("///"):
            doc.append(line[3:].strip())
            i += 1
            continue
        m = re.match(r"^(model|enum) (\w+) \{", line)
        if not m:
            if line and not line.startswith("//"):
                doc = []
            i += 1
            continue
        kind, name = m.groups()
        body = []
        i += 1
        while lines[i].strip() != "}":
            body.append(lines[i])
            i += 1
        i += 1
        if kind == "enum":
            enums[name] = [b.strip() for b in body if b.strip() and not b.strip().startswith("//")]
            doc = []
            continue
        table = {"model": name, "table": name, "section": section, "doc": " ".join(doc),
                 "columns": [], "relations": [], "pk": []}
        doc = []
        field_doc: list[str] = []
        for raw in body:
            s = raw.strip()
            if s.startswith("///"):
                field_doc.append(s[3:].strip())
                continue
            if not s or s.startswith("//"):
                continue
            if s.startswith("@@"):
                mm = re.match(r'@@map\("([^"]+)"\)', s)
                if mm:
                    table["table"] = mm.group(1)
                mm = re.match(r"@@id\(\[([^\]]+)\]\)", s)
                if mm:
                    table["pk"] = [f.strip() for f in mm.group(1).split(",")]
                continue
            fm = re.match(r"^(\w+)\s+(\w+)(\[\])?(\?)?\s*(.*)$", s)
            if not fm:
                continue
            fname, ftype, is_list, optional, attrs = fm.groups()
            attrs = re.sub(r"\s//.*$", "", attrs)
            if ftype in models:
                rm = re.search(r"fields:\s*\[([^\]]+)\],\s*references:\s*\[([^\]]+)\]", attrs)
                if rm:
                    table["relations"].append({"field": rm.group(1).strip(), "parent": ftype})
                field_doc = []
                continue
            column = re.search(r'@map\("([^"]+)"\)', attrs)
            table["columns"].append({
                "field": fname,
                "name": column.group(1) if column else fname,
                "type": _sql_type(ftype, attrs, enum_names),
                "optional": bool(optional),
                "id": "@id" in attrs,
                "unique": "@unique" in attrs,
            })
            field_doc = []
        tables.append(table)
    by_model = {t["model"]: t for t in tables}
    for t in tables:
        for c in t["columns"]:
            c["pk"] = c["id"] or c["field"] in t["pk"]
        for r in t["relations"]:
            col = next(c for c in t["columns"] if c["field"] == r["field"])
            col["fk"] = by_model[r["parent"]]["table"]
            r.update(column=col["name"], parent_table=col["fk"], optional=col["optional"], unique=col["unique"])
    return tables, enums


def _entity(t: dict, colour: str, keys_only: bool = False, stub: bool = False) -> str:
    rows_pk, rows = [], []
    for c in t["columns"]:
        tags = []
        if c["pk"]:
            tags.append("PK")
        if c.get("fk"):
            tags.append("FK")
        if c["unique"] and not c["pk"]:
            tags.append("UQ")
        if (keys_only or stub) and not tags:
            continue
        if stub and not c["pk"]:
            continue
        mark = "* " if not c["optional"] else "  "
        tag = f" <<{', '.join(tags)}>>" if tags else ""
        row = f"  {mark}{c['name']} : {c['type']}{tag}"
        (rows_pk if c["pk"] else rows).append(row)
    body = "\n".join(rows_pk) + ("\n  --\n" + "\n".join(rows) if rows else "")
    return f'entity "{t["table"]}" as {t["table"]} {colour} {{\n{body}\n}}\n'


def _relation(t: dict, r: dict) -> str:
    child = "|o" if r["unique"] else "}o"
    parent = "o|" if r["optional"] else "||"
    return f'{t["table"]} {child}--{parent} {r["parent_table"]} : {r["column"]}\n'


def erd_diagrams(root: Path) -> dict[str, str]:
    tables, enums = parse_schema((root / SCHEMA).read_text(encoding="utf8"))
    sections = list(dict.fromkeys(t["section"] for t in tables))
    colour = {s: SECTION_COLOURS[i % len(SECTION_COLOURS)] for i, s in enumerate(sections)}
    head = (HEADER.format(source=SCHEMA)
            + "!include ../style.iuml\nset separator none\nhide circle\nhide empty methods\nskinparam linetype ortho\n")
    out = {}

    # Overview: every table with its keys.
    text = f"@startuml erd-overview\n{head}"
    text += f"title PostgreSQL 18: all {len(tables)} tables and their foreign keys (keys only)\n"
    for s in sections:
        text += f'package "{s}" {{\n'
        text += "".join(_entity(t, colour[s], keys_only=True) for t in tables if t["section"] == s)
        text += "}\n"
    text += "".join(_relation(t, r) for t in tables for r in t["relations"])
    text += ("legend right\n  * required (NOT NULL)   PK primary key   FK foreign key   UQ unique\n"
             "  Prisma's own table _prisma_migrations is not shown.\nendlegend\n@enduml\n")
    out["erd-overview"] = text

    # One diagram per part, with every column; tables from other parts as stubs.
    for name, title, wanted in C.ERD_PARTS:
        mine = [t for t in tables if any(t["section"].startswith(w) for w in wanted)]
        if not mine:
            raise ValueError(f"{name}: no tables in sections {wanted}; check ERD_PARTS in contents.py")
        names = {t["table"] for t in mine}
        parents = {r["parent_table"] for t in mine for r in t["relations"]} - names
        text = f"@startuml {name}\n{head}title {title}\n"
        text += "".join(_entity(t, colour[t["section"]]) for t in mine)
        text += "".join(_entity(t, "#f1f5f9", stub=True) for t in tables if t["table"] in parents)
        text += "".join(_relation(t, r) for t in mine for r in t["relations"])
        used = sorted({c["type"] for t in mine for c in t["columns"] if c["type"] in enums})
        for e in used:
            text += f"enum {e} {{\n" + "\n".join(f"  {v}" for v in enums[e]) + "\n}\n"
        for t in mine:
            if t["doc"]:
                note = re.sub(r"(.{1,60})(\s+|$)", r"\1\n", t["doc"]).strip()
                text += f"note bottom of {t['table']}\n{note}\nend note\n"
        text += "legend right\n  * required (NOT NULL)   PK primary key   FK foreign key   UQ unique\nendlegend\n@enduml\n"
        out[name] = text
    return out


# --- The API (access matrix and AI contract) --------------------------------


def parse_access_matrix(text: str) -> list[dict]:
    routes = []
    for m in re.finditer(r"^\| (GET|POST|PUT|PATCH|DELETE) \| `([^`]+)` \| ([^|]+) \| ([^|]+) \|", text, re.M):
        method, path, rule, roles = (g.strip() for g in m.groups())
        roles = [r.strip() for r in roles.split(",") if r.strip() and r.strip() not in ("–", "-", "â€“")]
        routes.append({"method": method, "path": path, "rule": rule.replace("`", ""), "roles": roles})
    return routes


def api_diagram(root: Path) -> dict[str, str]:
    routes = parse_access_matrix((root / ACCESS_MATRIX).read_text(encoding="utf8"))
    groups: dict[str, list[dict]] = {title: [] for title, _ in C.API_GROUPS}
    for r in routes:
        segment = r["path"].removeprefix("/api/v1/").split("/")[0]
        title = next((t for t, segs in C.API_GROUPS if segment in segs), None)
        if title is None:
            raise ValueError(f"API route {r['path']}: add '{segment}' to API_GROUPS in contents.py")
        groups[title].append(r)
    ai_paths = re.findall(r"^  (/[^:]+):\s*\n((?:    .*\n)+)", (root / AI_CONTRACT).read_text(encoding="utf8"), re.M)

    text = f"@startuml api-map\n{HEADER.format(source=f'{ACCESS_MATRIX} and {AI_CONTRACT}')}"
    text += ("!include ../style.iuml\nallowmixing\nset separator none\nhide circle\nhide empty methods\n"
             "left to right direction\nskinparam ranksep 90\n")
    text += f"title The REST API: {len(routes)} routes under /api/v1, who may call them, and the AI service's internal API\n"
    text += 'actor "Phone app\\n(patients, clinicians,\\npathologists)" as phone\n'
    text += 'actor "Admin website\\n(administrators)" as admin\n'
    staff = {"PATIENT", "CLINICIAN", "PATHOLOGIST"}
    for i, (title, items) in enumerate(groups.items()):
        if not items:
            continue
        text += f'class "{title}" as g{i} <<{len(items)} routes>> {{\n'
        for r in items:
            who = ", ".join(x.title() for x in r["roles"]) or "anyone"
            text += f"  {{field}} {r['method']} {r['path'].removeprefix('/api/v1')}  ·  {r['rule']}  ·  {who}\n"
        text += "}\n"
        roles = {x for r in items for x in r["roles"]}
        public = any(r["rule"] == "public" for r in items)
        if roles & staff or public:
            text += f"phone --> g{i}\n"
        if "ADMIN" in roles or public:
            text += f"admin --> g{i}\n"
    text += 'class "AI service (internal; service token)" as aisvc <<FastAPI>> {\n'
    for path, block in ai_paths:
        for method in re.findall(r"^    (get|post|put|delete):", block, re.M):
            text += f"  {{field}} {method.upper()} {path}\n"
    text += "}\n"
    ai_group = next(f"g{i}" for i, (t, _) in enumerate(groups.items()) if t == C.API_AI_GROUP)
    chat_group = next(f"g{i}" for i, (t, _) in enumerate(groups.items()) if t == C.API_CHAT_GROUP)
    fhir_group = next(f"g{i}" for i, (t, _) in enumerate(groups.items()) if t == C.API_FHIR_GROUP)
    text += f"{ai_group} --> aisvc : /v1/infer\n{chat_group} --> aisvc : /v1/chat/answer\n"
    text += f'entity "SmartCare Pro\\n(FHIR R4, HTTPS)" as smartcare #f1f5f9\n{fhir_group} --> smartcare : push\n'
    text += ("legend right\n  Each line: method, path, permission, roles that have it by default.\n"
             "  An arrow means the app's users have permission for at least one route in the group.\n"
             "  Every route except the public ones needs a valid access token.\n"
             "  Administrators can change role permissions (within locks).\nendlegend\n@enduml\n")
    return {"api-map": text}


# --- The actual timeline (Git history) ---------------------------------------


def gantt_actual(root: Path) -> dict[str, str]:
    log = subprocess.run(
        ["git", "log", "--reverse", "--no-merges", "--date=short", "--format=%ad|%h|%s"],
        cwd=root, capture_output=True, text=True, encoding="utf8", check=True,
    ).stdout.splitlines()
    items = []
    for line in log:
        date, sha, subject = line.split("|", 2)
        if re.match(r"^(chore|Initial commit)", subject):
            continue
        label = re.sub(r"^\w+(\([^)]*\))?:\s*", "", subject)
        label = label[0].upper() + label[1:]
        if len(label) > 78:
            label = label[:75].rstrip() + "..."
        label = label.replace("[", "(").replace("]", ")")
        items.append((date, sha, label))
    if not items:
        return {}
    text = f"@startgantt gantt-actual\n{HEADER.format(source='the Git history (git log)')}"
    text += "!include ../style.iuml\n<style>\nganttDiagram {\n  milestone { BackGroundColor #1d4ed8 }\n}\n</style>\n"
    text += f"title What was built, day by day: one diamond per commit ({items[0][0]} to {items[-1][0]})\n"
    text += f"printscale daily\nProject starts {items[0][0]}\nsaturday are open\nsunday are open\nhide footbox\n"
    for date, sha, label in items:
        text += f"[{label} ({sha})] happens {date}\n"
    text += "@endgantt\n"
    return {"gantt-actual": text}


def generate(root: Path, out: Path) -> list[str]:
    """Writes the generated diagram sources; returns their names."""
    out.mkdir(parents=True, exist_ok=True)
    made = {**erd_diagrams(root), **api_diagram(root), **gantt_actual(root)}
    for old in out.glob("*.puml"):
        if old.stem not in made:
            old.unlink()
    for name, text in made.items():
        (out / f"{name}.puml").write_text(text, encoding="utf8", newline="\n")
    return list(made)
