"""Pydantic models mirroring 2-api-gateway/openapi/ai-contract.yaml (backend <-> AI boundary)."""

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, model_validator

Provenance = Literal["MOCK", "RESEARCH_MODEL"]
Architecture = Literal["UNET", "RESNET50", "ANN", "PATCH_CNN_MIL", "XGBOOST_FUSION"]

#: The only disclaimer a MOCK result may carry (contract rule).
MOCK_DISCLAIMER = "DEVELOPMENT MOCK DATA — NOT A CLINICAL RESULT."

#: Disclaimer for results from a registered research model (none exist yet).
RESEARCH_DISCLAIMER = (
    "Research model output for decision support only. "
    "It is not a diagnosis; a qualified clinician must interpret it."
)


class _Strict(BaseModel):
    model_config = ConfigDict(extra="forbid")


class ModelInfo(_Strict):
    name: str
    architecture: Architecture
    version: str
    provenance: Provenance
    #: Only from a stored evaluation run; never invented.
    evaluation: dict[str, object] | None = None


class ClinicalInputs(_Strict):
    ageYears: int | None = Field(default=None, ge=18, le=120)
    psaNgMl: float | None = Field(default=None, ge=0)
    freePsaNgMl: float | None = Field(default=None, ge=0)
    dreFinding: (
        Literal["NORMAL", "ENLARGED_SMOOTH", "NODULAR", "INDURATED", "NOT_PERFORMED"] | None
    ) = None
    piradsScore: int | None = Field(default=None, ge=1, le=5)
    prostateVolumeMl: float | None = Field(default=None, gt=0)
    biopsyHistory: Literal["NONE", "PRIOR_NEGATIVE", "PRIOR_POSITIVE", "UNKNOWN"] | None = None
    familyHistory: bool | None = None

    def has_findings(self) -> bool:
        """True when there is at least one measurement the clinical module could use."""
        return any(
            v is not None
            for v in (self.psaNgMl, self.freePsaNgMl, self.dreFinding, self.piradsScore)
        )


# Storage keys as generated by the backend: lower-case path segments, no traversal.
_STORAGE_KEY = r"^[a-z0-9][a-z0-9._-]*(/[a-z0-9][a-z0-9._-]*)*$"


class ImagingInput(_Strict):
    storageKey: str = Field(pattern=_STORAGE_KEY, max_length=512)
    modality: Literal["MRI", "TRUS", "CT"]


class SlideInput(_Strict):
    storageKey: str = Field(pattern=_STORAGE_KEY, max_length=512)
    stain: str | None = Field(default=None, max_length=40)


class InferenceInputs(_Strict):
    clinical: ClinicalInputs | None = None
    imaging: list[ImagingInput] = Field(default_factory=list, max_length=20)
    histopathology: list[SlideInput] = Field(default_factory=list, max_length=20)


class InferenceRequest(_Strict):
    jobId: UUID
    #: Opaque pseudonym from the backend, never a patient id or name.
    patientRef: str = Field(min_length=8, max_length=128, pattern=r"^[A-Za-z0-9_-]+$")
    inputs: InferenceInputs


class Explanation(_Strict):
    kind: Literal["GRADCAM", "SHAP", "MIL_ATTENTION"]
    module: str
    storageKey: str | None = None
    values: dict[str, float] | None = None
    unavailableReason: str | None = None

    @model_validator(mode="after")
    def _artifact_or_reason(self) -> "Explanation":
        # NFR-09: an explanation is either real (artifact or values) or says why not.
        has_artifact = self.storageKey is not None or self.values is not None
        if has_artifact == (self.unavailableReason is not None):
            raise ValueError("an explanation needs an artifact or an unavailableReason, not both")
        return self


class SkippedModule(_Strict):
    module: str
    reason: str


class InferenceOutputs(_Strict):
    pcaProbability: float | None = Field(default=None, ge=0, le=1)
    probabilityInterval: tuple[float, float] | None = None
    gleasonGradeGroup: int | None = Field(default=None, ge=1, le=5)
    segmentationMaskKey: str | None = None
    modulesUsed: list[str] = Field(default_factory=list)
    modulesSkipped: list[SkippedModule] = Field(default_factory=list)


class InferenceResult(_Strict):
    jobId: UUID
    provenance: Provenance
    disclaimer: str
    modelVersions: dict[str, str]
    outputs: InferenceOutputs
    explanations: list[Explanation]

    @model_validator(mode="after")
    def _mock_is_labelled(self) -> "InferenceResult":
        if self.provenance == "MOCK" and self.disclaimer != MOCK_DISCLAIMER:
            raise ValueError("a MOCK result must carry the mock disclaimer")
        return self
